# Generated by Django 4.0 on 2021-12-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('price', models.CharField(default='', max_length=100)),
                ('details', models.TextField(default='')),
                ('fileupload', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
