# Generated by Django 4.0 on 2021-12-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_table_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_product',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='table_product',
            name='fileupload',
            field=models.FileField(upload_to='product'),
        ),
    ]
