# Generated by Django 4.0 on 2022-01-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_table_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_product',
            name='quantity',
            field=models.CharField(default='', max_length=100),
        ),
    ]
