# Generated by Django 4.0 on 2022-01-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_table_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=100)),
                ('product_id', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('quantity', models.CharField(default='', max_length=100)),
                ('total', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
