# Generated by Django 4.0 on 2022-01-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_table_cart_product_id_alter_table_cart_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.table_user')),
            ],
        ),
    ]
